= Datomic->Crux Live converter

WARNING: This is alpha software, consider carefully before using.  However it has covered some common ground, so may capture more cases than a new rewrite would.

== Rationale

If you have a pre-existing system utilizing Datomic, it's a big requirement that you migrate in a single shot to another database.
Due to the similarity of Datomic & Crux, it may be possible to do a live sync of Datomic & Crux in order to make an incremental migration.

== Implemented

A live Datomic to Crux sync can happen for entities via REPL interactions.

== API

The main namespace is `io.dominic.datomic->crux.core`.
The conventional require is `[io.dominic.datomic->crux.core :as datomic->crux]`.

Notable functions:

`wrap-datomic-queue`:: This will wrap the result of `(d/tx-report-queue conn)` into a manifold stream appropriate for passing to other functions.  The purpose of this is to allow multiple subscribers to the datomic stream, you may not want to use this if you for example want to wrap into a manifold pubsub bus.
`subscribe-datomic`:: Takes a `stream`, `conn`, and `system` (Crux).  This will listen for transactions in Datomic and use this to trigger a catch up in Crux.  The loop ends when the stream is closed.
`subscribe-datomic-bg`:: Like `subscribe-datomic` but runs in a thread, you may not want to use this if you have an existing thread strategy.

== Missing

* Bidirectional sync
* Tx time preservation
